// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOneTodo(arg1:string):Promise<main.Todo>;

export function GetTodos():Promise<Array<main.Todo>>;

export function InsertTodo(arg1:string):Promise<main.Todo>;

export function ToggleTodo(arg1:string):Promise<main.Todo>;
