// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOneTodo(arg1) {
  return window['go']['main']['App']['GetOneTodo'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function InsertTodo(arg1) {
  return window['go']['main']['App']['InsertTodo'](arg1);
}

export function ToggleTodo(arg1) {
  return window['go']['main']['App']['ToggleTodo'](arg1);
}
